# fly.toml file generated for holy-feather-3465 on 2022-12-17T18:39:08+01:00

app = "holy-feather-3465"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "ghost:5.25.5"

[env]
  url = "https://holy-feather-3465.fly.dev"
  database__client = "sqlite3"
  database__connection__filename = "content/data/ghost.db"
  database__useNullAsDefault = "true"
  database__debug = "false"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[mounts]
  source="data"
  destination="/var/lib/ghost/content"

[[services]]
  http_checks = []
  internal_port = 2368
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
